server:
  port: 8092

spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-grouo
  datasource:
    url: jdbc:h2:mem:test:db
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  logging:
    file: C:\Users\91961\Desktop\library-events-consumer\server.log
  h2:
    console:
      enabled: true

---
spring:
  profiles: dev
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group


---
spring:
  profiles: prod
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeSerializer
      group-id: library-events-listener-grouo



